"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Production MUST set a real SECRET_KEY via the environment -- this dev
# fallback is intentionally marked "insecure" by Django's own convention and
# must never be used outside local development.
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-9(8)7j@=qieb5r!t39t91do&7=ado&lt&d9nuinuv%+@%kj9-a"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = [h.strip() for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'apps.accounts',
    'apps.kyc',
    'corsheaders',
    'apps.content',
    'apps.learning_paths',
    'django_celery_results',
    'apps.rewards',
    'apps.referrals',
    'apps.creator',
    'apps.notifications',
    'apps.ads',
    'apps.subscriptions',
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

if os.environ.get("DB_NAME"):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get("DB_NAME"),
            'USER': os.environ.get("DB_USER", ""),
            'PASSWORD': os.environ.get("DB_PASSWORD", ""),
            'HOST': os.environ.get("DB_HOST", "localhost"),
            'PORT': os.environ.get("DB_PORT", "5432"),
        }
    }
else:
    # Dev fallback: SQLite, used throughout this project's development.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# Development default: the console backend prints each email (verification links, password
# resets) to the `runserver` terminal instead of sending it.
# PRODUCTION MUST configure a real transactional email service (SendGrid, AWS SES, Mailgun,
# etc.) via the environment variables below, otherwise no user will ever receive a
# verification or password-reset email.
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "1") == "1"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "Digitize Pakistan <no-reply@digitize.com.pk>")

# Base URL of the Next.js frontend, used to build links inside emails.
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000")

# Hard ceiling for signed email tokens; individual flows enforce shorter limits (see emails.py).
PASSWORD_RESET_TIMEOUT = 3 * 24 * 3600

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

# Production sets CORS_ALLOWED_ORIGINS via the environment (comma-separated,
# e.g. "https://digitize.com.pk,https://www.digitize.com.pk") -- the
# localhost:3000 dev default is preserved as a fallback so local development
# is unaffected.
_cors_env = os.environ.get("CORS_ALLOWED_ORIGINS", "")
if _cors_env:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_env.split(",") if o.strip()]
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
    ]

CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "django-db"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://localhost:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

CELERY_BEAT_SCHEDULE = {
    "evaluate-referral-qualifications": {
        "task": "apps.referrals.tasks.evaluate_referral_qualifications",
        "schedule": 300.0,
    },
}

REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = [
    "apps.accounts.throttles.AtomicScopedRateThrottle",
]
REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
    "read_engagement": "20/min",
    "read_start": "60/min",
    "withdrawal": "5/hour",
    "register": "10/hour",
    "login": "10/min",
    "subscription": "5/hour",
    "password_change": "5/hour",
    "deactivate": "5/hour",
    "email_verification": "3/hour",
    "email_verify_confirm": "20/hour",
    "password_reset": "5/hour",
}

SIMPLE_JWT = {
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# Uploaded KYC documents / payment receipts. Deliberately NOT served via MEDIA_URL:
# files are only retrievable through staff-gated views. Production must use
# access-controlled (private) storage, not a public bucket.
MEDIA_ROOT = BASE_DIR / "private_media"
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024


# Media storage (KYC documents, avatars, payment receipts).
# https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html
#
# Dev fallback: local disk (FileSystemStorage, via MEDIA_ROOT above) — unchanged from before
# this file added R2 support. Set R2_ACCESS_KEY_ID (plus the other R2_* vars below) in
# production to switch to Cloudflare R2, an S3-compatible object store, via django-storages.
#
# The R2 bucket is PRIVATE (confirmed at creation, not public) -- files are never served via a
# public bucket URL. Two things keep that true in this codebase:
#   1. Every uploaded field (KYCRecord.cnic_front/cnic_back/selfie/document_file,
#      SubscriptionRequest.receipt_file, User.avatar) is only ever exposed through a
#      staff/owner-gated Django view (apps/kyc/admin.py, apps/subscriptions/admin.py,
#      apps/accounts/views.py MeAvatarView) that streams the file server-side via boto3
#      credentials -- it never renders or redirects to field.url, so R2 credentials, not bucket
#      publicity, are what gate access.
#   2. QUERYSTRING_AUTH is still enabled (with a short expiry) as defense in depth, in case
#      anything (e.g. Django admin's default FileField widget on the legacy/collapsed
#      document_file field) ever renders `.url` directly -- that URL is a time-limited signed
#      link, not a permanent public one.
R2_ACCESS_KEY_ID = os.environ.get("R2_ACCESS_KEY_ID", "")
R2_SECRET_ACCESS_KEY = os.environ.get("R2_SECRET_ACCESS_KEY", "")
R2_BUCKET_NAME = os.environ.get("R2_BUCKET_NAME", "")
R2_ENDPOINT_URL = os.environ.get("R2_ENDPOINT_URL", "")

# Explicit so this file's fallback is self-contained rather than relying on Django's
# implicit global_settings default -- functionally identical to that default either way.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
}

if R2_ACCESS_KEY_ID:
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key": R2_ACCESS_KEY_ID,
            "secret_key": R2_SECRET_ACCESS_KEY,
            "bucket_name": R2_BUCKET_NAME,
            "endpoint_url": R2_ENDPOINT_URL,
            "region_name": "auto",  # R2 doesn't use AWS regions; boto3 requires a value
            "default_acl": None,  # R2 doesn't support canned ACLs the way S3 does
            "file_overwrite": False,
            "querystring_auth": True,  # signed URLs, not public links -- see note above
            "querystring_expire": 3600,  # 1 hour
        },
    }
# else: STORAGES["default"] keeps Django's built-in FileSystemStorage default (MEDIA_ROOT
# above), exactly as before R2 support existed -- no change to local dev behavior.
