# Generated by Django 6.1.1 on 2026-09-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('KYC', 'KYC'), ('REWARD', 'Reward'), ('REFERRAL', 'Referral'), ('CREATOR', 'Creator'), ('CONTENT', 'Content'), ('SUBSCRIPTION', 'Subscription')], default='SYSTEM', max_length=20),
        ),
    ]
