# Generated by Django 6.1.1 on 2026-09-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='alternatives',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'TOOL_LISTING'}, related_name='alternative_to', to='content.content'),
        ),
        migrations.AddField(
            model_name='content',
            name='cons',
            field=models.TextField(blank=True, help_text='One short point per line.'),
        ),
        migrations.AddField(
            model_name='content',
            name='pricing_info',
            field=models.TextField(blank=True, help_text="Free text, one pricing line per line (e.g. 'Free tier available')."),
        ),
        migrations.AddField(
            model_name='content',
            name='pros',
            field=models.TextField(blank=True, help_text='One short point per line.'),
        ),
    ]
