# Generated by Django 6.1.1 on 2026-09-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('HOMEPAGE_HERO', 'Homepage Hero'), ('ARTICLE_INLINE', 'Article Inline'), ('SIDEBAR', 'Sidebar'), ('FOOTER', 'Footer')], max_length=30)),
                ('slot_type', models.CharField(choices=[('ADSENSE', 'Google AdSense'), ('DIRECT', 'Direct Advertiser')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('ad_client', models.CharField(blank=True, help_text='e.g. ca-pub-XXXXXXXXXX', max_length=50)),
                ('ad_slot_id', models.CharField(blank=True, max_length=50)),
                ('advertiser_name', models.CharField(blank=True, max_length=150)),
                ('image_url', models.URLField(blank=True)),
                ('target_url', models.URLField(blank=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
