# Generated by Django 6.1.1 on 2026-09-18 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_rs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('EASYPAISA', 'Easypaisa'), ('JAZZCASH', 'JazzCash'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20)),
                ('account_ref', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
