# Generated by Django 6.1.1 on 2026-09-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_rewardsledgerentry_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardrule',
            name='type',
            field=models.CharField(choices=[('READ_ENGAGEMENT', 'Read Engagement'), ('REFERRAL_BONUS', 'Referral Bonus'), ('CREATOR_BOUNTY', 'Creator Bounty'), ('SIGNUP_BONUS', 'Signup Bonus')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rewardsledgerentry',
            name='type',
            field=models.CharField(choices=[('READ_ENGAGEMENT', 'Read Engagement'), ('REFERRAL_BONUS', 'Referral Bonus'), ('CREATOR_BOUNTY', 'Creator Bounty'), ('SIGNUP_BONUS', 'Signup Bonus'), ('WITHDRAWAL', 'Withdrawal'), ('ADJUSTMENT', 'Adjustment')], max_length=20),
        ),
    ]
