# Generated by Django 6.1.1 on 2026-10-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_readsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardrule',
            name='type',
            field=models.CharField(choices=[('READ_ENGAGEMENT', 'Read Engagement'), ('REFERRAL_BONUS', 'Referral Bonus'), ('CREATOR_BOUNTY', 'Creator Bounty'), ('SIGNUP_BONUS', 'Signup Bonus'), ('LEARNING_PATH_COMPLETION', 'Learning Path Completion')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rewardsledgerentry',
            name='type',
            field=models.CharField(choices=[('READ_ENGAGEMENT', 'Read Engagement'), ('REFERRAL_BONUS', 'Referral Bonus'), ('CREATOR_BOUNTY', 'Creator Bounty'), ('SIGNUP_BONUS', 'Signup Bonus'), ('LEARNING_PATH_COMPLETION', 'Learning Path Completion'), ('WITHDRAWAL', 'Withdrawal'), ('ADJUSTMENT', 'Adjustment')], max_length=30),
        ),
    ]
