# Generated by Django 6.1.1 on 2026-09-24 15:33

import apps.kyc.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrequest',
            name='iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='receipt_file',
            field=models.ImageField(blank=True, upload_to=apps.kyc.validators.receipt_upload_path, validators=[apps.kyc.validators.validate_receipt_file]),
        ),
    ]
