# Generated by Django 6.1.1 on 2026-10-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_email_verified_user_unique_user_email_ci'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_alias_key',
            field=models.CharField(blank=True, editable=False, max_length=254, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('email_alias_key__isnull', False)), fields=('email_alias_key',), name='unique_user_email_alias_key'),
        ),
    ]
