# Generated by Django 6.1.1 on 2026-09-24 15:31

import apps.kyc.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycrecord',
            name='document_file',
            field=models.FileField(blank=True, upload_to=apps.kyc.validators.kyc_upload_path, validators=[apps.kyc.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='document_ref_url',
            field=models.URLField(blank=True),
        ),
    ]
