# Generated by Django 6.1.1 on 2026-09-24 16:08

import apps.kyc.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kycrecord_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycrecord',
            name='cnic_back',
            field=models.ImageField(blank=True, upload_to=apps.kyc.validators.kyc_upload_path, validators=[apps.kyc.validators.validate_receipt_file]),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='cnic_front',
            field=models.ImageField(blank=True, upload_to=apps.kyc.validators.kyc_upload_path, validators=[apps.kyc.validators.validate_receipt_file]),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='cnic_number',
            field=models.CharField(blank=True, max_length=15, validators=[apps.kyc.validators.validate_cnic_number]),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='selfie',
            field=models.ImageField(blank=True, upload_to=apps.kyc.validators.kyc_upload_path, validators=[apps.kyc.validators.validate_receipt_file]),
        ),
    ]
